### ISSUE TITLE
idea task - support TS tests

### ISSUE THREAD

**Issue by hugebdu** [wix/lerna-script#136]

**Comment by viliusl** [comment]
@hugebdu - could you please describe it better? I mean do you need preBuild script, args for mocha runner or such?

**Comment by hugebdu** [comment]
So we're experimenting with writing our IT tests in TypeScript instead of those typings.spec.ts to save some duplications.
That means our package.json#test has both `--register ts-node` and mocha patterns include `*.ts`, however autogenerated IDEA test configs don't have those.

@alexeevg suggested to check package.json and build our IDEA test configs according to `test:*` scripts we have.

**Comment by hugebdu** [comment]
already supported via `lerna.js` - closing
